-- banco de dados Associados
INSERT INTO ASSOCIADO(NOME, CARGO, DATA_NASCIMENTO, SEXO) VALUES ('Gilberto Nascimento JR', 'VEREADOR', '1967-10-25', 'MASCULINO');
INSERT INTO ASSOCIADO(NOME, CARGO, DATA_NASCIMENTO, SEXO) VALUES ('Robert Willians', 'PREFEITO', '1983-07-12', 'MASCULINO');
INSERT INTO ASSOCIADO(NOME, CARGO, DATA_NASCIMENTO, SEXO) VALUES ('Maria Dolores da Cunha', 'DEPUTADO_ESTADUAL', '1999-05-17', 'FEMININO');
INSERT INTO ASSOCIADO(NOME, CARGO, DATA_NASCIMENTO, SEXO) VALUES ('Danilo Schudeller', 'DEPUTADO_FEDERAL', '1943-02-28', 'MASCULINO');
INSERT INTO ASSOCIADO(NOME, CARGO, DATA_NASCIMENTO, SEXO) VALUES ('Gustavo Salvato', 'SENADOR', '1978-11-15', 'MASCULINO');
INSERT INTO ASSOCIADO(NOME, CARGO, DATA_NASCIMENTO, SEXO) VALUES ('Luciana Silva', 'GOVERNADOR', '1988-12-05', 'FEMININO');
INSERT INTO ASSOCIADO(NOME, CARGO, DATA_NASCIMENTO, SEXO) VALUES ('Gustavo Betete', 'PRESIDENTE', '1999-05-12', 'MASCULINO');


--banco de dados Partido
INSERT INTO PARTIDO(NOME_PARTIDO, SIGLA, IDEOLOGIA, DATA_FUNDACAO) VALUES ('Partido da Social Democracia Brasileira', 'PSDB', 'CENTRO', '1988-06-25');
INSERT INTO PARTIDO(NOME_PARTIDO, SIGLA, IDEOLOGIA, DATA_FUNDACAO) VALUES ('Partido dos Trabalhadores', 'PT', 'ESQUERDA', '1980-02-10');
INSERT INTO PARTIDO(NOME_PARTIDO, SIGLA, IDEOLOGIA, DATA_FUNDACAO) VALUES ('Movimento Democrático Brasileiro', 'MDB', 'DIREITA', '1981-06-30');
INSERT INTO PARTIDO(NOME_PARTIDO, SIGLA, IDEOLOGIA, DATA_FUNDACAO) VALUES ('Progressistas', 'PP', 'CENTRO', '1995-11-16');
