INSERT INTO ASSOCIADO(NOME, CARGO_POLITICO, DATA_NASCIMENTO, SEXO) VALUES ('Jackson', 'Vereador', '1967-10-25', 'Masculino');
INSERT INTO PARTIDO(NOME_PARTIDO, SIGLA, IDEOLOGIA, DATA_FUNDACAO) VALUES ('Partido da Social Democracia Brasileira', 'PSDB', 'Centro', '1988-6-25');
